<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro" name="ceres_sap">
	<xacro:include filename="$(find sedna_description)/urdf/sedna.urdf.xacro"/>
	<xacro:include filename="asus_xtion_pro.urdf.xacro"/>
	

	<xacro:property name="cam_px" value="${body_length/2 - 0.01}" />
    <xacro:property name="cam_py" value="0.02" />
        <xacro:property name="cam_pz" value="${body_height + 0.69}" />
        <xacro:property name="cam_or" value="0.03" />
        <xacro:property name="cam_op" value="0.339" />
        <xacro:property name="cam_oy" value="0" />

	<xacro:sensor_asus_xtion_pro  parent="base_link"/>	
	<link name ="kinect_pole">
		<visual>
			<geometry>
				<box size="0.02 0.02 0.8"/>
			</geometry>
			<material name="silver" >
      				<color rgba="0.5 0.5 0.5 1" />
 			</material>
		</visual>
	</link>
	<joint name="base_to_kinect_pole" type="fixed">
		<parent link="base_link"/>
		<child link="kinect_pole"/>
		<origin xyz="${body_length/2 - 0.095} 0 ${body_height + 0.32}"/>
	</joint>
	<link name="kinect_support">
          <visual>
	    <geometry>
	      <box size="0.02 0.02 0.5" />
	    </geometry>
	    <origin rpy="0 0.4 0"/>
	    <material name="silver" >
              <color rgba="0.5 0.5 0.5 1" />
            </material>
	  </visual>
	</link>
	<joint name="base_to_kinect_support" type="fixed">
	  <parent link="base_link"/>
	  <child link="kinect_support"/>
	  <origin xyz="${0.085} -0.02 ${body_height + 0.15}" />
	</joint>	
</robot>
